### ISSUE TITLE
ProcessInstance.WaitForExitAsync throws exception if already exited

### ISSUE THREAD

**Issue by patagonaa** [rosenbjerg/Instances#2]
(I'm not sure if I should submit this here or in the FFMpegCore repo, but I'm pretty sure Instances is the cause, so I post it here)

Since version 4.8.0 of FFMpegCore (where Instances Version 2.0 was first used), AnalyzeAsync sometimes throws `Instances.Exceptions.InstanceProcessAlreadyExitedException`.
I guess this happens because FFProbe may exit before `ProcessInstance.WaitForExitAsync()` is waiting.

I don't really understand why `WaitForExitAsync`, `WaitForExit` or `Kill` should even throw Exceptions, if it's already exited, why not return immediately?

Stacktrace:
```
Instances.Exceptions.InstanceProcessAlreadyExitedException: The process instance has already exited
   at Instances.ProcessInstance.WaitForExit()
   at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler, EventHandler`1 errorHandler)
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String arguments, FFOptions ffOptions)
   at FFMpegCore.FFProbe.AnalyseAsync(String filePath, FFOptions ffOptions, CancellationToken cancellationToken)
[...]
```

**Comment by MrMoeinM** [comment]
Same here!

**Comment by AllegraMcdonnell123** [comment]
Same here, Any Idea how to fix it? 🍰

**Comment by rosenbjerg** [comment]
Version 3 has been uploaded to nuget.org
